version: '3'
services:
  mariadb:
    container_name: riotMariadb
    image: mariadb
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=riot
      - TZ=Europe/Paris
    ports:
      - "3306:3306"
    networks:
      api:
        ipv4_address: 172.16.220.2

  nginx:
    container_name: riotNginx
    image: nginx:stable-alpine
    depends_on:
      - php
    ports:
      - "8088:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      api:
        ipv4_address: 172.16.220.3
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riotPhp
    volumes:
      - ../:/var/www/html
    ports:
      - "9000:9000"
    networks:
      api:
        ipv4_address: 172.16.220.4

networks:
  api:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.220.0/24
